services:
  patterns:
    image: nginx:alpine
    container_name: patterns
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
      - "./compose/nginx.conf:/etc/nginx/nginx.conf"
      - "./compose/php.ini:/usr/local/etc/php/conf.d/php.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.patterns.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.patterns.entrypoints=websecure"
      - "traefik.http.routers.patterns.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
